### ISSUE TITLE
Setup https

### ISSUE THREAD

**Issue by Avsecz** [kipoi/website#66]

**Comment by zupan** [comment]
This commit is a response to the feedback from the community when some users observed issues accessing kipoi.org due to not having custom SSL certificates setup (which is not yet possible directly through the GitHub pages).

In order to overcome this problem, we have setup a proxy through the Cloudflare where we can set up also SSL certificate.

Issue will be closed once DNS records are updated and all traffic goes through Cloudflare.

**Comment by Avsecz** [comment]
works as a charm
